=== onlinebooks/Web1/data/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns="http://www.bibliotecadiportobuffole.com"
    targetNamespace="http://www.bibliotecadiportobuffole.com"
    elementFormDefault="qualified">

<xsd:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2001/xml.xsd"/>
<!--Tende alla Veneziana-->

<xsd:element name="biblioteca" type="tBiblioteca"/>

<xsd:complexType name="tBiblioteca">
	<xsd:sequence>
		<xsd:element name="Libri" type="tLibri"/>
		<xsd:element name="Utenti" type="tUtenti"/>
		<xsd:element name="Prenotazioni" type="tPrenotazioni"/>
		<xsd:element name="Prestiti" type="tPrestiti"/>
		<xsd:element name="Voti" type="tVoti"/>
		<xsd:element name="Commenti" type="tCommenti"/>
	</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="tLibri">
<xsd:sequence maxOccurs="unbounded">
<xsd:element name="libro" type="tLibro"/>
</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="tLibro">
<xsd:sequence>
<xsd:element name="titolo" type="xsd:string"/>
<xsd:element name="sottotitolo" type="xsd:string" minOccurs="0"/>
<xsd:element name="autore" type="tAutore" maxOccurs="unbounded"/>
<xsd:element name="annoPubblicazione" type="xsd:gYear"/>
<xsd:element name="edizione" type="tEdizione"/>
<xsd:element name="trama" type="testo"/>
<xsd:element name="copertina" type="Timg"/>
<xsd:element name="quantita" type="xsd:integer"/>
</xsd:sequence>
<xsd:attribute name="ISBN" type="tIsbn" use="required"/>
<xsd:attribute name="lang" type="xsd:language" use="required"/>
</xsd:complexType>

<xsd:complexType name="tAutore">
<xsd:sequence>
<xsd:element name="nome" type="xsd:string"/>
<xsd:element name="cognome" type="xsd:string"/>
<xsd:element name="secondoNome" type="xsd:string" minOccurs="0"/>
</xsd:sequence>
</xsd:complexType>

<xsd:simpleType name="tIsbn">
<xsd:restriction base="xsd:string">
<xsd:pattern value="\d{3}-\d{1,7}-\d{1,7}-\d{1,7}-\d{1}" />
<!--Il codice isbn e' formato di 13 cifre raggruppate in 5 settori. Solo il primo e l'ultimo hanno lunghezza fissa (risp. di 3 e 1 cifre)-->
</xsd:restriction>
</xsd:simpleType>

<xsd:complexType name="tEdizione">
<xsd:sequence>
<xsd:element name="casaEditrice" type="xsd:string"/>
<xsd:element name="edizione" type="xsd:integer" minOccurs="0"/>
<xsd:element name="collana" type="xsd:string" minOccurs="0"/>
<xsd:element name="annoEdizione" type="xsd:gYear" minOccurs="0"/>
<xsd:element name="ristampa" type="xsd:gYear" minOccurs="0"/>
</xsd:sequence>
</xsd:complexType>


<xsd:complexType name="testo">
<xsd:sequence minOccurs="1" maxOccurs="unbounded">
<xsd:element name="img" type="Timg" minOccurs="0"/>
<xsd:element name="p" type="TP" />
<xsd:element name="img" type="Timg" minOccurs="0"/>
</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="TP" mixed="true">
<xsd:choice minOccurs="0" maxOccurs="unbounded">
<xsd:element name="span" type="TSpan" />
<xsd:element name="a" type="TA" />
<xsd:element name="abbr" type="TAbbr" />
<xsd:element name="em" type="xsd:string"/>
<xsd:element name="strong" type="xsd:string"/>
<xsd:element name="img" type="Timg"/>
</xsd:choice>
</xsd:complexType>

<xsd:complexType name="TSpan">
<xsd:simpleContent>
<xsd:extension base="xsd:string">
<xsd:attribute ref="xml:lang" />
</xsd:extension>
</xsd:simpleContent>
</xsd:complexType>
	
<xsd:complexType name="TAbbr">
<xsd:simpleContent>
<xsd:extension base="xsd:string">
<xsd:attribute name="title" type="xsd:string" />
<xsd:attribute ref="xml:lang" />
</xsd:extension>
</xsd:simpleContent>
</xsd:complexType>

<xsd:complexType name="TA">
<xsd:simpleContent>
<xsd:extension base="xsd:string">
<xsd:attribute name="href" type="xsd:anyURI" use="required" />
<xsd:attribute ref="xml:lang" />
</xsd:extension>
</xsd:simpleContent>
</xsd:complexType>

<xsd:complexType name="Timg">
<xsd:attribute name="src" type="xsd:anyURI" use="required" />
<xsd:attribute name="alt" type="xsd:string" />
<xsd:attribute name="id" type="xsd:string" />
<xsd:attribute name="class" type="xsd:string" />
</xsd:complexType>




<xsd:complexType name="tUtenti">
	<xsd:sequence maxOccurs="unbounded">
		<xsd:element name="utente" type="tUtente"/>
	</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="tUtente">
	<xsd:sequence>
		<xsd:element name="user" type="xsd:ID"/>
		<xsd:element name="nome" type="xsd:string"/>
		<xsd:element name="secondoNome" type="xsd:string" minOccurs="0"/>
		<xsd:element name="cognome" type="xsd:string"/>
		<xsd:element name="annoNascita" type="xsd:integer"/>
		<xsd:element name="mail" type="tMail"/>
		<xsd:element name="numeroTessera" type="xsd:string" minOccurs="0"/>
		<xsd:element name="password" type="tPassword"/>
	</xsd:sequence>
</xsd:complexType>


<xsd:simpleType name="tMail"> 
    <xsd:restriction base="xsd:string"> 
      <xsd:pattern value="[a-zA-Z0-9\.]+@[a-zA-Z0-9\.\-]+\.[a-zA-Z]{2,4}"/> 
    </xsd:restriction> 
  </xsd:simpleType>

<xsd:simpleType name="tPassword"> 
    <xsd:restriction base="xsd:string"> 
      <xsd:pattern value=".{40}"/> 
    </xsd:restriction> 
  </xsd:simpleType>



<xsd:complexType name="tPrenotazioni">
	<xsd:sequence maxOccurs="unbounded" minOccurs="0">
		<xsd:element name="prenotazione" type="tPrenotazione"/>
	</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="tPrenotazione">
	<xsd:sequence>
		<xsd:element name="libro" type="tIsbn"/>
		<xsd:element name="utente" type="xsd:IDREF"/>
		<xsd:element name="dataInizio" type="xsd:date"/>
		<xsd:element name="dataFine" type="xsd:date"/>
		<xsd:element name="restituito" type="xsd:integer"/>
		<xsd:element name="dataRestituzione" type="xsd:date" minOccurs="0"/>
	</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="tPrestiti">
	<xsd:sequence maxOccurs="unbounded" minOccurs="0">
		<xsd:element name="prestito" type="tPrestito"/>
	</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="tPrestito">
	<xsd:sequence>
		<xsd:element name="libro" type="tIsbn"/>
		<xsd:element name="tesseraUtente" type="xsd:string"/>
		<xsd:element name="dataInizio" type="xsd:date"/>
		<xsd:element name="dataFine" type="xsd:date"/>
		<xsd:element name="restituito" type="xsd:integer"/>
		<xsd:element name="dataRestituzione" type="xsd:date" minOccurs="0"/>
	</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="tVoti">
	<xsd:sequence maxOccurs="unbounded" minOccurs="0">
		<xsd:element name="voto" type="tVoto"/>
	</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="tVoto">
	<xsd:sequence>
		<xsd:element name="libro" type="tIsbn"/>
		<xsd:element name="utente" type="xsd:IDREF"/>
		<xsd:element name="voto" type="xsd:decimal"/>
	</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="tCommenti">
	<xsd:sequence maxOccurs="unbounded" minOccurs="0">
		<xsd:element name="commento" type="tCommento"/>
	</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="tCommento">
	<xsd:sequence>
		<xsd:element name="libro" type="tIsbn"/>
		<xsd:element name="utente" type="xsd:IDREF"/>
		<xsd:element name="commento" type="testo"/>
	</xsd:sequence>
</xsd:complexType>

</xsd:schema>

=== onlinebooks/Web1/data/dati_old.xml
<?xml version="1.0" encoding="UTF-8"?>
<x:biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.bibliotecadiportobuffole.com" xmlns:x="http://www.bibliotecadiportobuffole.com"
 xsi:schemaLocation="http://www.bibliotecadiportobuffole.com schema.xsd">

<Libri>
	<libro ISBN="978-88-06-21646-7" lang="it">
	<titolo>Norwegian wood</titolo>
	<sottotitolo>Tokyo blues</sottotitolo>
	<autore>
		<nome>Haruki</nome>
		<cognome>Murakami</cognome>
	</autore>
	<annoPubblicazione>1987</annoPubblicazione>
	<edizione>
		<casaEditrice>Einaudi</casaEditrice>
		<edizione>1</edizione>
		<collana>Super ET</collana>
		<annoEdizione>2006</annoEdizione>
		<ristampa>2015</ristampa>
	</edizione>
	<trama>
	<p>Uno dei più clamorosi successi letterari giapponesi di tutti i tempi è anche il libro più intimo, introspettivo di Murakami, che qui si stacca dalle
	atmosfere oniriche e surreali che lo hanno reso famoso, per esplorare il mondo in ombra dei sentimenti e della solitudine.</p>
	<p><span xml:lang="en">Norwegian wood</span> è anche un grande romanzo sull'adolescenza, sul conflitto tra il desiderio di essere integrati nel mondo
	degli altri per entrare vittoriosi nella vita adulta e il bisogno irrinunciabile di essere sé stessi, costi quel che costi. Come il giovane Holden, Toru è continuamente assalito dal dubbio di aver sbagliato o poter sbagliare nelle sue scelte di vita e di amore, ma è anche guidato da un ostinato e personale senso della morale e da un'istintiva avversione per tutto ciò che sa di costruito. Diviso tra due ragazze, Naoko e Midori, che lo attirano entrambe con forza irresistibile, Toru non può fare altro che decidere. O aspettare che la vita(e la morte) decidano per lui.</p>
	</trama>
	<copertina src="resources/libri/Norwegian_wood.png" alt="copertina di Norwegian wood"/>
	<quantita>2</quantita>
	</libro>
</Libri>

<Utenti>
	<utente>
		<user>maario</user>
		<nome>Mario</nome>
		<cognome>Rossi</cognome>
		<annoNascita>1994</annoNascita>
		<mail>mariorossi@gmail.com</mail>
		<numeroTessera>000001</numeroTessera>
		<password>5baa61e4c9b93f3f0682250b6cf8331b7ee68fd8</password>
	</utente>
</Utenti>

<Prenotazioni>
	<prenotazione>
		<libro>978-88-06-21646-7</libro>
		<utente>maario</utente>
		<dataInizio>2016-04-12</dataInizio>
		<dataFine>2016-04-22</dataFine>
		<restituito>1</restituito>
		<dataRestituzione>2016-04-21</dataRestituzione>
	</prenotazione>
</Prenotazioni>

<Prestiti>
	<prestito>
		<libro>978-88-06-21646-7</libro>
		<tesseraUtente>000001</tesseraUtente>
		<dataInizio>2016-04-13</dataInizio>
		<dataFine>2016-04-22</dataFine>
		<restituito>1</restituito>
		<dataRestituzione>2016-04-21</dataRestituzione>
	</prestito>
</Prestiti>

<Voti>
	<voto>
		<libro>978-88-06-21646-7</libro>
		<utente>maario</utente>
		<voto>8.5</voto>
	</voto>
</Voti>

<Commenti>
	<commento>
		<libro>978-88-06-21646-7</libro>
		<utente>maario</utente>
		<commento><p>Questo libro è molto profondo.</p></commento>
	</commento>
</Commenti>
</x:biblioteca>

=== onlinebooks/Web1/data/dati.xml
<?xml version="1.0" encoding="UTF-8"?>
<x:biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.bibliotecadiportobuffole.com" xmlns:x="http://www.bibliotecadiportobuffole.com" xsi:schemaLocation="http://www.bibliotecadiportobuffole.com schema.xsd">

<Libri>
	<libro ISBN="978-88-06-21646-7" lang="it">
	<titolo>Norwegian wood</titolo>
	<sottotitolo>Tokyo blues</sottotitolo>
	<autore>
		<nome>Haruki</nome>
		<cognome>Murakami</cognome>
	</autore>
	<annoPubblicazione>1987</annoPubblicazione>
	<edizione>
		<casaEditrice>Einaudi</casaEditrice>
		<edizione>1</edizione>
		<collana>Super ET</collana>
		<annoEdizione>2006</annoEdizione>
		<ristampa>2015</ristampa>
	</edizione>
	<trama>
	<p>Uno dei più clamorosi successi letterari giapponesi di tutti i tempi è anche il libro più intimo, introspettivo di Murakami, che qui si stacca dalle
	atmosfere oniriche e surreali che lo hanno reso famoso, per esplorare il mondo in ombra dei sentimenti e della solitudine.</p>
	<p><span xml:lang="en">Norwegian wood</span> è anche un grande romanzo sull'adolescenza, sul conflitto tra il desiderio di essere integrati nel mondo
	degli altri per entrare vittoriosi nella vita adulta e il bisogno irrinunciabile di essere sé stessi, costi quel che costi. Come il giovane Holden, Toru è continuamente assalito dal dubbio di aver sbagliato o poter sbagliare nelle sue scelte di vita e di amore, ma è anche guidato da un ostinato e personale senso della morale e da un'istintiva avversione per tutto ciò che sa di costruito. Diviso tra due ragazze, Naoko e Midori, che lo attirano entrambe con forza irresistibile, Toru non può fare altro che decidere. O aspettare che la vita(e la morte) decidano per lui.</p>
	</trama>
	<copertina src="resources/libri/Norwegian_wood.png" alt="copertina di Norwegian wood"/>
	<quantita>1</quantita>
	</libro>
	<libro ISBN="978-1-85326-041-4" lang="en">
			<titolo>Il grande Gatsby</titolo><autore>
			<nome>Scott</nome>
			<cognome>Fitzgerald</cognome><secondoNome>Francis</secondoNome></autore>
			<annoPubblicazione>1925</annoPubblicazione>
			<edizione>
			<casaEditrice>Wordsorth classics</casaEditrice></edizione>
			<trama><p>Ambientato a <span xml:lang="en">New York</span> e a <span xml:lang="en">Long Island</span> durante l'estate del 1922, Il grande Gatsby è il più acuto ritratto dell'anima dell'età del <span xml:lang="en">jazz</span>, con le sue contraddizioni, il suo vittimismo e la sua tragicità. La storia, che seguendo la tecnica di <span xml:lang="en">Henry James</span> viene raccontata da uno dei personaggi, narra la tragedia del mito americano che aveva retto il paese dai tempi dello sbarco a <span xml:lang="en">Plymouth Rock</span> e può essere considerata l'autobiografia spirituale di Fitzgerald che, ad un certo punto della sua vita, chiuso con l'alcolismo e con la vita da <span xml:lang="en">playboy</span>, voleva capire quali fossero stati gli ostacoli che avevano fatto inabissare la sua esistenza.</p></trama>
			<copertina src="../Public_html/resources/copertineLibri/il_grande_gatsby.jpg" alt="Copertina del libro il grande Gatsby"/>
			<quantita>1</quantita>
			</libro>
			</Libri>

<Utenti>
	<utente>
		<user>mario94</user>
		<nome>Mario</nome>
		<cognome>Rossi</cognome>
		<annoNascita>1994</annoNascita>
		<mail>mariorossi@gmail.com</mail>
		<numeroTessera>000001</numeroTessera>
		<password>ciaograzie</password>
	</utente>
	<utente>
		<user>mario96</user>
		<nome>Mario</nome>
		<cognome>Rossi</cognome>
		<annoNascita>1994</annoNascita>
		<mail>mariorossi@gmail.com</mail>
		<numeroTessera>000001</numeroTessera>
		<password>ciaograzie</password>
	</utente>

				<utente>
					<user>zaidan90</user>
					<nome>Gino</nome>
					<cognome>Zaidan</cognome>
					<annoNascita>1990</annoNascita>
					<mail>zaidan90@hotmail.it</mail>
					<password>ciaograzie</password>
				</utente>				
				<utente>
					<user>fbizzaro</user>
					<nome>Francesco</nome>
					<cognome>Bizzaro</cognome>
					<annoNascita>1994</annoNascita>
					<mail>fbizzaro@gmail.com</mail>
					<password>123sweg123</password>
				</utente>
				<utente>
					<user>gbruni</user>
					<nome>Giorgio</nome>
					<cognome>Bruni</cognome>
					<annoNascita>1987</annoNascita>
					<mail>gbruni@gmail.com</mail>
					<password>ciaograzie</password>
				</utente>
				<utente>
					<user>enriquad</user>
					<nome>Enrico</nome>
					<cognome>Chiara</cognome>
					<annoNascita>1991</annoNascita>
					<mail>enriquad@gmail.com</mail>
					<password>ciaograzie</password>
				</utente>
				<utente>
					<user>boriky</user>
					<nome>Riccardo</nome>
					<cognome>Rizzo</cognome>
					<annoNascita>1993</annoNascita>
					<mail>boriky@gmail.com</mail>
					<password>ciaograzie</password>
				</utente>
				</Utenti>

<Prenotazioni>
	<prenotazione>
		<libro>978-88-06-21646-7</libro>
		<utente>maario</utente>
		<dataInizio>2016-04-12</dataInizio>
		<dataFine>2016-04-22</dataFine>
		<restituito>1</restituito>
		<dataRestituzione>2016-04-21</dataRestituzione>
	</prenotazione>
</Prenotazioni>

<Prestiti>
	<prestito>
		<libro>978-88-06-21646-7</libro>
		<tesseraUtente>000001</tesseraUtente>
		<dataInizio>2016-04-13</dataInizio>
		<dataFine>2016-04-22</dataFine>
		<restituito>1</restituito>
		<dataRestituzione>2016-04-21</dataRestituzione>
	</prestito>
</Prestiti>

<Voti>
	<voto>
		<libro>978-88-06-21646-7</libro>
		<utente>maario</utente>
		<voto>8.5</voto>
	</voto>
</Voti>

<Commenti>
	<commento>
		<libro>978-88-06-21646-7</libro>
		<utente>maario</utente>
		<commento><p>Questo libro è molto profondo.</p></commento>
	</commento>
</Commenti>
</x:biblioteca>
